version: '3'

services:
  netops-server:
    build: .
    container_name: netops-server
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - NODE_ENV=production
    restart: unless-stopped
